export const  GET_ITEM_REQUEST = "GET_ITEM_REQUEST";
export const  GET_ITEM_SUCSESS = "GET_ITEM_SUCSESS";
export const  GET_ITEM_RFAILURE = "GET_ITEM_RFAILURE";

export const  POST_ITEM_REQUEST = "POST_ITEM_REQUEST";
export const  POST_ITEM_SUCSESS = "POST_ITEM_SUCSESS";
export const  POST_ITEM_RFAILURE = "POST_ITEM_RFAILURE";

export const  PUT_ITEM_REQUEST = "PUT_ITEM_REQUEST";
export const  PUT_ITEM_SUCSESS = "PUT_ITEM_SUCSESS";
export const  PUT_ITEM_RFAILURE = "PUT_ITEM_RFAILURE";

export const  DELETE_ITEM_REQUEST = "DELETE_ITEM_REQUEST";
export const  DELETE_ITEM_SUCSESS = "DELETE_ITEM_SUCSESS";
export const  DELETE_ITEM_RFAILURE = "DELETE_ITEM_RFAILURE";

export const  SEARCH_ITEM_REQUEST = "SEARCH_ITEM_REQUEST";
export const  SEARCH_ITEM_SUCSESS = "SEARCH_ITEM_SUCSESS";
export const  SEARCH_ITEM_RFAILURE = "SEARCH_ITEM_RFAILURE";

export const  PAGINATION_PAGE_REQUEST = "PAGINATION_PAGE_REQUEST";
export const  PAGINATION_PAGE_SUCSESS = "PAGINATION_PAGE_SUCSESS";
export const  PAGINATION_PAGE_RFAILURE = "PAGINATION_PAGE_RFAILURE";

export const GET_NUMBER_PAGE ="GET_NUMBER_PAGE";
export const CHANGE_ACTIVE_PAGE ="CHANGE_ACTIVE_PAGE";
export const GET_ACTIVE_PAGE_TO_DEFAULT ="GET_ACTIVE_PAGE_TO_DEFAULT";
export const GET_VALUE_SEARCH ="GET_VALUE_SEARCH";

export const  GET_ALL_ITEM_REQUEST = "GET_ALL_ITEM_REQUEST";
export const  GET_ALL_ITEM_SUCSESS = "GET_ALL_ITEM_SUCSESS";
export const  GET_ALL_ITEM_RFAILURE = "GET_ALL_ITEM_RFAILURE";